apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elk-stack
data:
  elasticsearch.yml: |
    cluster.name: elk-cluster
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.watcher.enabled: false
    xpack.ml.enabled: false
    xpack.graph.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
